### ISSUE TITLE
[Stripe 4.7] CRITICAL Uncaught Error: Call to undefined function return__() in /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php:45

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gateway-stripe#1433]
**Describe the bug**

I can't figure out yet what is happening but I am seeing this critical error in the Stripe logs on the site:

```
2020-12-22T08:08:56+00:00 CRITICAL Uncaught Error: Call to undefined function return__() in /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php:45
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php(129): WC_Stripe_Inbox_Notes::get_success_title()
#1 /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php(203): WC_Stripe_Inbox_Notes::create_marketing_note()
#2 /wordpress/core/5.6/wp-includes/class-wp-hook.php(287): WC_Stripe_Inbox_Notes::cleanup_campaign_2020()
#3 /wordpress/core/5.6/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#4 /wordpress/core/5.6/wp-includes/plugin.php(551): WP_Hook->do_action(Array)
#5 /wordpress/core/5.6/wp-cron.php(138): do_action_ref_array('wc_stripe_apple...', Array)
#6 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php on line 45
```

Note that this is happening on one of our Atomic test sites. The Cart and Checkout pages are blank on that site for some reason after adding a product to the cart - see gif below:

http://recordit.co/VFeW0KRMNF

This issue, however, is present even after I deactivate Stripe. It doesn't look like Stripe is what is causing the blank cart and checkout page though but I figured I'd provide for the reference. 

**To Reproduce**

Sorry, this is not one of my best reports as I am not sure how to reproduce this. Still investigating on the site what is going on. This doesn't happen on any of our other test sites (non-Atomic). 

If you'd like to test yourself on that Atomic site in question, you can get credentials here ( see `ATOMIC TEST SITE:` section): Pb22l9-t-p2. 

I will add more details to this issue as soon as I find out.  

**Expected behavior**

I expected not to see no critical errors in the Stripe logs. 

**Screenshots**

![Screen Shot 2020-12-22 at 4 33 09 PM](https://user-images.githubusercontent.com/19143190/102935085-6caae900-4473-11eb-86b0-4154ed23703d.png)

Note that I have a message saying `The public and/or secret keys for the Stripe gateway have been changed. This might cause errors for existing customers and saved payment methods. Click here to learn more.`. I am yet to take care of that. I will be able to confirm after I am done with it if this is what had caused an issue by any chance. 

**Environment (please complete the following information):**

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://atomic1.testwc.com
Site address (URL): https://atomic1.testwc.com
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.1
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.25
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: wp_
Total Database Size: 4.09MB
Database Data Size: 2.60MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 1.38MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 45
customize_changeset: 7
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 6
page: 18
post: 14
product: 14
revision: 116
shop_coupon: 1
shop_order: 17
shop_order_refund: 7
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Jetpack by WordPress.com: by Automattic – 9.2.1
Password Protected: by Ben Huson – 2.4
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce Stripe Gateway: by WooCommerce – 4.7.0
WooCommerce: by Automattic – 4.9.0-beta.1

### Inactive Plugins (10) ###

AMP: by AMP Project Contributors – 2.0.9
Classic Editor: by WordPress Contributors – 1.6
CoBlocks: by GoDaddy – 2.5.3
Contact Form 7: by Takayuki Miyoshi – 5.3.2
Gutenberg: by Gutenberg Team – 9.5.2
Layout Grid: by Automattic – 1.3
Page Optimize: by Automattic – 0.5.1
WooCommerce Blocks: by Automattic – 4.0.0
WordPress.com Editing Toolkit: by Automattic – 2.8.16
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.0.9


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #51 - /
Cart: ❌ Page does not contain the shortcode.
Checkout: ❌ Page does not contain the shortcode.
My account: #54 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.0.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 32
Oldest: 2020-11-22 02:18:42 +0000
Newest: 2020-12-22 21:18:54 +0000

`
```
</details>

**Additional context**

N/A

**Comment by juliaamosova** [comment]
Closing this issue after chatting with @dechov on Slack and confirming that the error was logged when Stripe was still on 4.6.
