### ISSUE TITLE
Potential conflict with Elementor Pro

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/woocommerce-gateway-stripe#2579]
Case 1: https://wordpress.org/support/topic/call-to-undefined-method-stripe-gateway/
Case 2: 6044068-zen

**Describe the bug**

When the most recent order has a refund (Order Refund object) - a page that is built with Elementor and that contains "My Account" module from Elementor Pro, crashes when we try to edit it using Elementor builder

**To Reproduce**

1. Install Stripe and purchase two products
2. Refund one of them in the order
3. Create a page with Elementor Pro and add My Account module to it, publish.
4. View the page and try to edit it again with Elementor 

```
:  Uncaught Error: Call to undefined method Automattic\WooCommerce\Admin\Overrides\OrderRefund::get_payment_method() in /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php:848
Stack trace:
#0 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php(786): WC_Gateway_Stripe->verify_intent_after_checkout(Object(Automattic\WooCommerce\Admin\Overrides\OrderRefund))
#1 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/class-wp-hook.php(308): WC_Gateway_Stripe->check_intent_status_on_order_page(67)
#2 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/my-account.php(1972): do_action('woocommerce_acc...', 67)
#5 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/my-account.php(1789): ElementorPro\Modules\Woocommerce\Widgets\My_Account->render_html_editor()
#6 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/includes/base/controls-stack.php(2268): ElementorPro\Modules\Woocommerce\Widgets\My_Account->render()
#7 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#8 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base->render_content()
#9 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/includes/base/element-base.php(536): Elementor\Widget_Base->get_raw_data(true)
#10 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/includes/base/element-base.php(536): Elementor\Element_Base->get_raw_data(true)
#11 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/core/base/document.php(966): Elementor\Element_Base->get_raw_data(true)
#12 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/core/base/document.php(632): Elementor\Core\Base\Document->get_elements_raw_data(Array, true)
#13 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/includes/base/controls-stack.php(1021): Elementor\Core\Base\Document->get_initial_config()
#14 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/core/editor/editor.php(383): Elementor\Controls_Stack->get_config()
#15 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->enqueue_scripts('')
#16 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#17 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#18 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/script-loader.php(2180): do_action('wp_enqueue_scri...')
#19 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts('')
#20 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#21 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#22 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/general-template.php(3043): do_action('wp_head')
#23 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#24 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/core/editor/editor-loader.php(113): include('/Applications/M...')
#25 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/elementor/core/editor/editor.php(172): Elementor\Core\Editor\Editor_Loader->print_root_template()
#26 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->init('')
#27 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#28 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#29 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-admin/admin.php(419): do_action('admin_action_el...')
#30 /Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-admin/post.php(12): require_once('/Applications/M...')
#31 {main}
  thrown in Applications/MAMP/htdocs/woogenerator/sites/wp-7265081/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 848
```

In both cases, Elementor support has indicated this issue needs to be fixed on Stripe plugin so I am opening this report for developers to check.

It appears that there's an attempt to access `get_payment_method()` function which is a method in Order object but not in Order Refund object.

**Comment by dougaitken** [comment]
Hey @kaushikasomaiya - can this be replicated on another site? I see `woogenerator` in the log file, was this your own test or the merchant?

**Comment by kaushikasomaiya** [comment]
Hi @dougaitken Yes, I am able to reproduce this on my test site. The logs are from my own test site but matches with the merchant's logs.

**Comment by rally-lad** [comment]
Just encountered the same issue this morning too. Exactly the same as the above.

**Comment by robbdeveloper** [comment]
same issue here... 3 months already and nothing solved I see.

**Comment by namiokuzono** [comment]
Possibly the same issue is reported here 6329106-zen

Cross-checking [this report](https://github.com/Automattic/woocommerce-payments/issues/2616) as well (though this one is a different kind of issue).
