### ISSUE TITLE
Fatal when extends WC_Gateway_Stripe

### ISSUE THREAD

**Issue by salvoyith** [woocommerce/woocommerce-gateway-stripe#2938]
**Describe the bug**
I created a custom gateway that extends WC_Gateway_Stripe, and when enable the option **New checkout experience** and try to pay an order in the checkout block page, a fatal error is generated : 

` PHP Fatal error:  Uncaught Error: Call to undefined method YITH_WC_Subscription_WC_Stripe::get_upe_enabled_at_checkout_payment_method_ids() in /Users/salvatorestrano/LocalSites/wc-blocks/app/public/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php:1289`

The problem is that the class WC_Gateway_Stripe use the method  _get_upe_enabled_at_checkout_payment_method_ids_ but isn't not declarated here but in the class WC_Stripe_UPE_Payment_Gateway at line 391

**Environment:**

WordPress Version 6.4.3
WooCommerce Version 8.6.1
Stripe Plugin Version 7.9.3

**Comment by mrkarp-atomic** [comment]
Hello,

When turning off the Legacy Mode checkbox in the payment settings area, we are now receiving some errors and failures for missing methods : `PHP Fatal error:  Uncaught Error: Call to undefined method WC_Gateway_Stripe::get_upe_enabled_at_checkout_payment_method_ids() in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php:1323`

Here is our code:
  `$gateway = new WC_Gateway_Stripe();`
  `$intent = $gateway->create_intent( $order, $prepared_source ); //TODO: Error currently with Legacy Mode`

I have narrowed it it down to:
wp-content\plugins\woocommerce-gateway-stripe\includes\abstracts\abstract-wc-stripe-payment-gateway.php

`$payment_method_types = [ 'card' ];`
		`if ( WC_Stripe_Feature_Flags::is_upe_checkout_enabled() ) {`
			`$payment_method_types = $this->get_upe_enabled_at_checkout_payment_method_ids(); // @phpstan-ignore-line (get_upe_enabled_at_checkout_payment_method_ids is defined in the classes that use this class)`
		`} elseif ( isset( $prepared_source->source_object->type ) ) {`
			`$payment_method_types = [ $prepared_source->source_object->type ];`
		`}`

Which now includes a comment about it being ignored and in other classes.

Here is the full stacktrace:
`PHP Fatal error:  Uncaught Error: Call to undefined method WC_Gateway_Stripe::get_upe_enabled_at_checkout_payment_method_ids() in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php:1323\nStack trace:\n#0 /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php(1456): WC_Stripe_Payment_Gateway->generate_create_intent_request(Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order), Object(stdClass))\n#1 /var/www/html/wp-content/plugins/custom-charge-on-ship/includes/custom-charge-on-ship-woocommerce.php(215): WC_Stripe_Payment_Gateway->create_intent(Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order), Object(stdClass))\n#2 /var/www/html/wp-content/plugins/custom-charge-on-ship/includes/custom-charge-on-ship-woocommerce.php(137): create_new_payment_intent_and_capture(Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order), 'pm_0Q2dotGT64ku...')\n#3 /var/www/html/wp-includes/class-wp-hook.php(324): charge_on_ship_hook(20, Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order), Array)\n#4 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-order.php(411): do_action('woocommerce_ord...', 20, Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order), Array)\n#7 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-order.php(253): WC_Order->status_transition()\n#8 /var/www/html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php(768): WC_Order->save()\n#9 /var/www/html/wp-includes/class-wp-hook.php(326): WC_Meta_Box_Order_Data::save(20)\n#10 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#11 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#12 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php(313): do_action('woocommerce_pro...', 20, Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order))\n#13 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php(153): Automattic\\WooCommerce\\Internal\\Admin\\Orders\\Edit->handle_order_update()\n#14 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php(350): Automattic\\WooCommerce\\Internal\\Admin\\Orders\\Edit->setup(Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order))\n#15 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php(366): Automattic\\WooCommerce\\Internal\\Admin\\Orders\\PageController->prepare_order_edit_form()\n#16 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php(167): Automattic\\WooCommerce\\Internal\\Admin\\Orders\\PageController->setup_action_edit_order()\n#17 [internal function]: Automattic\\WooCommerce\\Internal\\Admin\\Orders\\PageController->handle_load_page_action('')\n#18 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Traits/AccessiblePrivateMethods.php(158): call_user_func_array(Array, Array)\n#19 /var/www/html/wp-includes/class-wp-hook.php(324): Automattic\\WooCommerce\\Internal\\Admin\\Orders\\PageController->__call('handle_load_pag...', Array)\n#20 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#21 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#22 /var/www/html/wp-admin/admin.php(237): do_action('load-woocommerc...')\n#23 {main}\n  thrown in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php on line 1323, referer: /wp-admin/admin.php?page=wc-orders&action=edit&id=20`

**Comment by Mayisha** [comment]
`get_upe_enabled_at_checkout_payment_method_ids ` is a function in the `WC_Stripe_UPE_Payment_Gateway` class.

When you disable the 'legacy checkout experience' (meaning you are using the 'new checkout experience'), you have to extend the `WC_Stripe_UPE_Payment_Gateway` class instead (not the `WC_Gateway_Stripe` class).

```
$gateway = new WC_Stripe_UPE_Payment_Gateway();
```

**Comment by mrkarp-atomic** [comment]
Thank you @Mayisha!! We were able to extend the `WC_Stripe_UPE_Payment_Gateway` class and it worked perfectly.
