### ISSUE TITLE
Php fatal error 8.0

### ISSUE THREAD

**Issue by pimihel** [woocommerce/woocommerce-gateway-stripe#2967]
PHP Fatal error: Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /www/xxxxxxx/public/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php:661

**Comment by galbaras** [comment]
This seems weird, considering that `$gateways` contains the Stripe gateway reference as a minimum, and the function is called via a core WC hook. Maybe you can try to isolate this further by looking for other messages that could be related and performing a plugin/theme isolation test.

Also, it'll be helpful to provide environment information, like PHP version, web server information, WordPress version and the versions of WooCommerce and the Stripe Gateway plugin.

**Comment by marcus-abrahamsson** [comment]
Same issue here. 

Checked the logs and the only errors are this. All plugins and theme is up to date.

PHP: 8.1.27
Webserver: NGINX 1.25.4
WordPress: 6.4.3 
Stripe Gateway: 8.1

NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php:661
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php(661): array_keys()
#1 /var/www/html/wp-includes/class-wp-hook.php(324): WC_Gateway_Stripe->reorder_available_payment_gateways()
#2 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#3 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(333): apply_filters()
#4 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php(391): WC_Payment_Gateways->get_available_payment_gateways()
#5 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php(80): Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->get_incentive()
- -  28/Mar/2024:08:52:48 +0000 "GET /wp-admin/index.php" 500
#6 /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php(98): Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->must_be_visible()
#7 /var/www/html/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->register_payments_welcome_page()
#8 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#9 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#10 /var/www/html/wp-admin/includes/menu.php(161): do_action()
#11 /var/www/html/wp-admin/menu.php(417): require_once('...')
#12 /var/www/html/wp-admin/admin.php(158): require('...')
#13 /var/www/html/wp-admin/index.php(10): require_once('...')
#14 {main}
  thrown in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 661

**Comment by galbaras** [comment]
When does this happen? How can it be reproduced? What are the plugin settings (except the secret bits)?

**Comment by marcus-abrahamsson** [comment]
When trying to access wp admin. No matter what page in admin. Get wp critical error message. Haven’t changed any settings before or after update. Default settings.

**Comment by galbaras** [comment]
The function `reorder_available_payment_gateways()` is called by the `woocommerce_available_payment_gateways` filter hook in the function `get_available_payment_gateways()`, where the first line ensures that the filter function always gets an array, so again, I really wonder how this is happening.

Can you perhaps download the plugin and reinstall it?

Also, can you compare the contents of wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on your server [the Github version](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b6d2a25be62373c976f6167acdc5756528c2033e/includes/class-wc-gateway-stripe.php)?

**Comment by Mayisha** [comment]
This issue was fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3136.
