### ISSUE TITLE
Fatal error on product page related to SEPA

### ISSUE THREAD

**Issue by joffreypersia** [woocommerce/woocommerce-gateway-stripe#2983]
In my product page (single product template), I have the error : 
```
Fatal error: Uncaught ValueError: Unknown format specifier "i" in /home/u646416831/domains/imane-ayissi.com/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-method-sepa.php:61 Stack trace: #0 /home/u646416831/domains/imane-ayissi.com/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-method-sepa.php(61): sprintf() #1 /home/u646416831/domains/imane-ayissi.com/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php(428): WC_Stripe_UPE_Payment_Method_Sepa->get_testing_instructions() #2 /home/u646416831/domains/imane-ayissi.com/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php(359): WC_Stripe_UPE_Payment_Gateway->get_enabled_payment_method_config() #3 /home/u646416831/domains/imane-ayissi.com/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php(308): WC_Stripe_UPE_Payment_Gateway->javascript_params() #4 /home/u646416831/domains/imane-ayissi.com/public_html/wp-includes/class-wp-hook.php(324): WC_Stripe_UPE_Payment_Gateway->payment_scripts() #5 /home/u646416831/domains/imane-ayissi.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #6 /home/u646416831/domains/imane-ayissi.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #7 /home/u646416831/domains/imane-ayissi.com/public_html/wp-includes/general-template.php(3068): do_action() #8 /home/u646416831/domains/imane-ayissi.com/public_html/wp-content/themes/bricks/footer.php(12): wp_footer() #9 /home/u646416831/domains/imane-ayissi.com/public_html/wp-includes/template.php(790): require_once('/home/u64641683...') #10 /home/u646416831/domains/imane-ayissi.com/public_html/wp-includes/template.php(725): load_template() #11 /home/u646416831/domains/imane-ayissi.com/public_html/wp-includes/general-template.php(92): locate_template() #12 /home/u646416831/domains/imane-ayissi.com/public_html/wp-content/themes/bricks/single-product.php(60): get_footer() #13 /home/u646416831/domains/imane-ayissi.com/public_html/wp-includes/template-loader.php(106): include('/home/u64641683...') #14 /home/u646416831/domains/imane-ayissi.com/public_html/wp-blog-header.php(19): require_once('/home/u64641683...') #15 /home/u646416831/domains/imane-ayissi.com/public_html/index.php(17): require('/home/u64641683...') #16 {main} thrown in/home/u646416831/domains/imane-ayissi.com/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-method-sepa.phpon line61
```

**Environment (please complete the following information):**
 - WordPress Version 6.4.3
 - WooCommerce Version 8.6.1
 - Stripe Plugin Version 8.0.0
 - MacOs Chrome up to date 

**Additional context**

**Comment by galbaras** [comment]
[The reported line](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3af922613975402e23cab9cc90f59304860b1a14/includes/payment-methods/class-wc-stripe-upe-payment-method-sepa.php#L61) doesn't seem to have anything relevant to the error message. Is it possible your file is different?

**Comment by csmcneill** [comment]
> WordPress Version 6.4.3
> WooCommerce Version 8.6.1
> Stripe Plugin Version 8.0.0

All of these items are out of date:
- The latest version of WordPress is 6.5
- The latest version of WooCommerce is 8.7
- The latest version of the Stripe WooCommerce Extension is 8.1.1

I'd recommend updating your software and determining if this resolves the issue.

**Comment by ericfri** [comment]
8844194-zen

**Comment by laurendavissmith** [comment]
I've been unable to reproduce so I'm going to close this for now but we can reopen once we get reproducible steps.
