### ISSUE TITLE
Admin area timing out with Stripe 8.1.1

### ISSUE THREAD

**Issue by theabhig** [woocommerce/woocommerce-gateway-stripe#3048]
**Describe the bug**

We have seen a couple of reports in tickets and in the form about the latest version of Stripe causing the WordPress admin area to time out and become inaccessible. The front end of the site has remained unaffected.

In 7964121-zen this was resolved by rolling back to the previous version. In this [Forum thread](https://wordpress.org/support/topic/probleme-avec-woocommerce-stripe-gateways/#post-17554133), the error persisted even after a conflict test.

There haven't been a large number of reports of this so far, but would be worth investigating just in case.

The full error is:

```
2024-04-05T11:08:00+00:00 Critical Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/vhosts/___/httpdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php:660 
CONTEXT: {
  "error":{
    "type":1,
    "file":"/var/www/vhosts/___/httpdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php",
    "line":660
  },
  "backtrace":[
    "",
    "#0 /var/www/vhosts/___/httpdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php(660): array_keys()",
    "#1 /var/www/vhosts/___/httpdocs/wp-includes/class-wp-hook.php(324): WC_Gateway_Stripe->reorder_available_payment_gateways()",
    "#2 /var/www/vhosts/___/httpdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()",
    "#3 /var/www/vhosts/___/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(333): apply_filters()",
    "#4 /var/www/vhosts/___/httpdocs/wp-content/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php(391): WC_Payment_Gateways->get_available_payment_gateways()",
    "#5 /var/www/vhosts/___/httpdocs/wp-content/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php(80): Automattic\\WooCommerce\\Internal\\Admin\\WcPayWelcomePage->get_incentive()",
    "#6 /var/www/vhosts/___/httpdocs/wp-content/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php(98): Automattic\\WooCommerce\\Internal\\Admin\\WcPayWelcomePage->must_be_visible()",
    "#7 /var/www/vhosts/___/httpdocs/wp-includes/class-wp-hook.php(324): Automattic\\WooCommerce\\Internal\\Admin\\WcPayWelcomePage->register_payments_welcome_page()",
    "#8 /var/www/vhosts/___/httpdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()",
    "#9 /var/www/vhosts/___/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action()",
    "#10 /var/www/vhosts/___/httpdocs/wp-admin/includes/menu.php(161): do_action()",
    "#11 /var/www/vhosts/___/httpdocs/wp-admin/menu.php(422): require_once('...')",
    "#12 /var/www/vhosts/___/httpdocs/wp-admin/admin.php(158): require('...')",
    "#13 {main}",
    "thrown"
  ]
}
```

**To Reproduce**

I haven't been able to reproduce it and neither were the developers in Slack but felt it was worth investigating.

**Additional Context**

p1712320577685009-slack-C7U3Y3VMY

**Comment by csmcneill** [comment]
This seems to be the same error reported in #2967

**Comment by Mayisha** [comment]
This issue was fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3136.
