### ISSUE TITLE
Bug: Undefined array key 0 in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-customer.php on line 241; PHP message: id was called incorrectly

### ISSUE THREAD

**Issue by karsey24** [woocommerce/woocommerce-gateway-stripe#3413]
**Describe the bug**
An error is reported to users when attempting to place an order.  Their card is charged, and they are emailed, but the order process fails at some step.

**To Reproduce**
1. Add an item to the cart
2. Checkout
3. Enter all required information
4. Press the final button required to place an order

**Expected behavior**
Order should be placed.  An order should be visible to site admins, emails should be sent, payment method should be charged, and any fulfilment steps should be taken.

**Error Log**
` Got error 'PHP message: PHP Warning:  Undefined array key 0 in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-customer.php on line 241; PHP message: id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Stripe_UPE_Payment_Gateway->process_payment, WC_Stripe_UPE_Payment_Gateway->process_payment_with_deferred_intent, WC_Stripe_Payment_Gateway->process_response, WC_Order->payment_complete, apply_filters('woocommerce_payment_complete_order_status'), WP_Hook->apply_filters, freebie_check, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_status_pending_to_processing_notification'), WP_Hook->do_a...; PHP message: PHP Fatal error:  Uncaught TypeError: Automattic\\WooCommerce\\Utilities\\OrderUtil::remove_status_prefix(): Argument #1 ($status) must be of type string, null given, called in /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 629 and defined in /var/www/html/wp-content/plugins/woocommerce/src/Utilities/OrderUtil.php:239\nStack trace:\n#0 /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(629): Automattic\\WooCommerce\\Utilities\\OrderUtil::remove_status_prefix()\n#1 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-order.php(286): WC_Abstract_Order->set_status()\n#2 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-order.php(150): WC_Order->set_status()\n#3 /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php(590): WC_Order->payment_complete()\n#4 /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-metho...', referer: https://mycustom.karsey.com/checkout/
[Tue Sep 03 15:57:42.501913 2024] [proxy_fcgi:error] [pid 1528261:tid 139763548178176] [remote 162.245.182.65:0] AH01071: Got error 'PHP message: id was called incorrectly. Order properties should not be accessed directly. Backtrace: do_action('wp_ajax_woocommerce_refund_line_items'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::refund_line_items, wc_create_refund, do_action('woocommerce_order_fully_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_fully_refunded_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Refunded_Order->trigger_full, WC_Email_Customer_Refunded_Order->trigger, WC_Email->get_content, WC_Email_Customer_Refunded_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-refunded-order.php'), do_action('woocommerce_email_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails->order_details, wc_get_template, include('/themes/myc-theme-store/woocommerce/emails/email-order-details.php'), WC_Order->get_order_item_totals, ...', referer: https://mycustom.karsey.com/wp-admin/post.php?post=91545&action=edit`

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 8.2.23
PHP Post Max Size: 200 MB
PHP Time Limit: 3000
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.30
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 266
custom_css: 1
nav_menu_item: 10
oembed_cache: 10
page: 17
post: 36
product: 123
product_variation: 17
revision: 176
seedprod: 1
shop_coupon: 379
shop_order: 12909
shop_order_refund: 98
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

Clover Payments for WooCommerce: by Clover eCommerce – 1.0.12
Debug Bar: by wordpressdotorg – 1.1.6
Site Kit by Google: by Google – 1.134.0
Offload Media - Cloud Storage: by Acowebs – 1.1.11
Custom Salesforce integration: by Custom – 1.4.0
Custom  Store Features: by Custom – 1.0.0
Simple Cloudflare Turnstile: by Elliot Sowersby
RelyWP – 1.27.0

User Role Editor: by Vladimir Garagulya – 4.64.2
WooCommerce.com Update Manager: by Automattic – 1.0.3
Avalara AvaTax: by Avalara – 2.8.0
Woo Conditional Shipping and Payments: by Woo – 2.0.3
WooCommerce Amazon Pay: by WooCommerce – 2.5.2
Clover for WooCommerce: by Kestrel – 5.2.6
WooCommerce Stripe Gateway: by WooCommerce – 8.6.1
WooCommerce PayPal Payments: by WooCommerce – 2.9.0
WooCommerce PDF Invoices: by Andrew Benbow – 5.0.5
WooCommerce: by Automattic – 9.2.2 (update to version 9.2.3 is available)
WordPress Importer: by wordpressdotorg – 0.8.2
Yoast SEO: by Team Yoast – 23.4
WP Consent API: by RogierLankhorst – 1.0.7
WP Mail SMTP Pro: by WP Mail SMTP – 4.1.1
WordPress Multisite Content Copier/Updater: by Obtain Infotech – 2.0.2
Cloudflare: by Cloudflare
Inc. – 4.12.8

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Safe SVG: by 10up – 2.2.6
User Switching: by John Blackbourn – 1.8.0
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
WP Mail SMTP Pro: by WP Mail SMTP – 4.1.1
Cookie banner plugin for WordPress – Cookiebot CMP by Usercentrics: by Usercentrics A/S – 4.3.9
W3 Total Cache: by BoldGrid – 2.7.5
WP Migrate Lite: by WP Engine – 2.6.11

### Inactive Plugins (26) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Broken Link Checker: by WPMU DEV – 2.3.0
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: by SeedProd – 6.18.5
DigitalOcean Spaces Sync: by keeross – 2.2.1
Facebook for WooCommerce: by Facebook – 3.2.8
Order Export & Order Import for WooCommerce: by WebToffee – 2.5.6
PublishPress Future: by PublishPress – 3.4.4
Query Monitor: by John Blackbourn – 3.16.4
Scrollsequence (Premium): by Scrollsequence – 1.5.6
myc-blocks — CGB Gutenberg Block Plugin: by mrahmadawais
maedahbatool – 1.0.0

Solid Security Pro: by SolidWP – 8.4.2
My Custom API: by My Custom – 1.0.0
My Custom Auto Scale Image: by My Custom – 0.1.0
My Custom Content Plugin: by My Custom – 1.5.0
My Custom Customer Portal: by My Custom – 1.0.0
My Custom Event: by My Custom – 0.1.0
My Custom Photo Gallery Image: by The WordPress Contributors – 0.1.0
My Custom Service Portal Features: by My Custom – 1.1.0
My Custom Tagged Product Scroll: by My Custom – 0.1.0
SSL Insecure Content Fixer: by WebAware – 2.7.2
WooCommerce Blocks: by Automattic – 11.7.0
WooCommerce Shipping & Tax: by WooCommerce – 2.8.0
WP Crontrol: by John Blackbourn – 1.17.0
WP fail2ban: by Charles Lecklider – 5.3.2
WP fail2ban Blocklist: by Charles Lecklider – 2.2.1
YouTube WordPress Plugin Pro by Embed Plus: by Embed Plus for YouTube Team – 14.2.1.2

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php
object-cache.php: object-cache.php

### Must Use Plugins (1) ###

WP Migrate Lite Compatibility: by Delicious Brains – 1.3

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 866 KB

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #8 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set
s
### Theme ###

Name: MY Store
Version: 1.0.1
Author URL: https://www.mycustom.karsey.com
Child Theme: ✔
Parent Theme Name: MY Store Theme
Parent Theme Version: 1.0.3
Parent Theme Author URL: https://wordpress.org
WooCommerce Support: ✔

### Templates ###

Overrides: myc-theme/woocommerce/archive-product.php
myc-theme-store/woocommerce/cart/cart-empty.php
myc-theme-store/woocommerce/cart/cart-shipping.php version 7.3.0 is out of date. The core version is 8.8.0
myc-theme-store/woocommerce/cart/cart-totals.php
myc-theme-store/woocommerce/cart/cart.php
myc-theme-store/woocommerce/cart/mini-cart.php
myc-theme-store/woocommerce/cart/proceed-to-checkout-button.php
myc-theme/woocommerce/checkout/form-billing.php
myc-theme/woocommerce/checkout/form-checkout.php
myc-theme-store/woocommerce/checkout/payment.php
myc-theme-store/woocommerce/checkout/thankyou.php
myc-theme-store/woocommerce/content-product.php
myc-theme-store/woocommerce/content-single-product.php
myc-theme-store/woocommerce/emails/admin-failed-order.php
myc-theme-store/woocommerce/emails/customer-invoice.php
myc-theme-store/woocommerce/emails/customer-processing-order.php
myc-theme-store/woocommerce/emails/email-order-details.php
myc-theme-store/woocommerce/global/breadcrumb.php
myc-theme-store/woocommerce/global/quantity-input.php
myc-theme-store/woocommerce/global/wrapper-start.php
myc-theme/woocommerce/loop/loop-end.php
myc-theme/woocommerce/loop/loop-start.php
myc-theme/woocommerce/loop/pagination.php
myc-theme-store/woocommerce/myaccount/form-add-payment-method.php
myc-theme-store/woocommerce/myaccount/form-edit-account.php version 7.0.1 is out of date. The core version is 8.7.0
myc-theme-store/woocommerce/myaccount/form-edit-address.php
myc-theme-store/woocommerce/myaccount/form-login.php version 7.0.1 is out of date. The core version is 9.2.0
myc-theme-store/woocommerce/myaccount/form-lost-password.php version 7.0.1 is out of date. The core version is 9.2.0
myc-theme-store/woocommerce/myaccount/form-reset-password.php version 7.0.1 is out of date. The core version is 9.2.0
myc-theme-store/woocommerce/myaccount/lost-password-confirmation.php
myc-theme-store/woocommerce/myaccount/my-account.php
myc-theme-store/woocommerce/myaccount/my-address.php version 2.6.0 is out of date. The core version is 9.2.0
myc-theme-store/woocommerce/myaccount/my-orders.php
myc-theme-store/woocommerce/myaccount/navigation.php version 2.6.0 is out of date. The core version is 9.0.0
myc-theme-store/woocommerce/myaccount/orders.php version 7.8.0 is out of date. The core version is 9.2.0
myc-theme-store/woocommerce/myaccount/payment-methods.php version 7.8.0 is out of date. The core version is 8.9.0
myc-theme-store/woocommerce/notices/error.php version 3.9.0 is out of date. The core version is 8.6.0
myc-theme-store/woocommerce/notices/notice.php version 3.9.0 is out of date. The core version is 8.6.0
myc-theme-store/woocommerce/notices/success.php version 3.9.0 is out of date. The core version is 8.6.0
myc-theme-store/woocommerce/order/order-details-item.php
myc-theme-store/woocommerce/single-product/add-to-cart/simple.php
myc-theme-store/woocommerce/single-product/add-to-cart/variable.php
myc-theme-store/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
myc-theme-store/woocommerce/single-product/meta.php
myc-theme-store/woocommerce/single-product/price.php
myc-theme-store/woocommerce/single-product/product-image.php version 7.8.0 is out of date. The core version is 9.0.0
myc-theme-store/woocommerce/single-product/product-thumbnails.php
myc-theme-store/woocommerce/single-product/related.php
myc-theme-store/woocommerce/single-product/tabs/description.php
myc-theme-store/woocommerce/single-product/tabs/tabs.php
myc-theme-store/woocommerce/single-product/title.php
myc-theme-store/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-09-04 15:52:21 -05:00
Options: ✔
Notes: 215
Onboarding: completed

### Action Scheduler ###

Complete: 603
Oldest: 2024-08-03 11:50:00 -0500
Newest: 2024-09-03 11:27:26 -0500

Failed: 14
Oldest: 2023-02-22 21:06:41 -0600
Newest: 2024-08-30 11:56:02 -0500

Pending: 9
Oldest: 2024-09-03 11:32:08 -0500
Newest: 2024-09-06 06:11:25 -0500


### pdf-invoices ###

PHP Version: ✔ Version 8.2.23 is installed.
DOMDocument: ✔ Version 20031129 is installed.
PCRE: ✔ Version 8.2.23 is installed.
Zlib: ✔ Version 8.2.23 is installed.
ZipArchive: ✔ Version 1.21.1 is installed.
ICONV: ✔ Version 2.31 is installed.
MBString: ❌ Multibyte Support is required
please contact your host to have it installed.

GD: ❌ Required if you have images in your PDFs
PDF Generator: ✔ DOMPDF
Order status to create invoice: ✔ Processing
Set Resources Folder: ✔ False
Remote Logo: ✔ True
Which date does the invoice use?: ✔ Completed
PDF Creation Method: ✔ Standard
New order email: ❌ No. Recipient : redacted@gmail.com
Cancelled order email: ❌ No. Recipient : redacted@gmail.com
Failed order email: ❌ No. Recipient : redacted@gmail.com
Order on-hold email: ❌ No. Recipient : customer
Processing order email: ✔ Yes
using template file Template. Recipient : customer

Completed order email: ❌ No. Recipient : customer
Refunded order email: ❌ No. Recipient : customer
Order details email: ❌ No. Recipient : customer
Customer note email: ❌ No. Recipient : customer
Reset password email: ❌ No. Recipient : customer
New account email: ❌ No. Recipient : customer
Failed Subscription Renewal SCA Authentication email: ❌ No. Recipient : customer
Pre-order Payment Action Needed email: ❌ No. Recipient : customer
Payment Authentication Requested Email email: ❌ No. Recipient : redacted@gmail.com

### Status report information ###

Generated at: 2024-09-03 11:32:39 -05:00
```
</details>

**Comment by karsey24** [comment]
This might be easier to read:

```[03-Sep-2024 18:36:32 UTC] PHP Fatal error:  Uncaught TypeError: Automattic\WooCommerce\Utilities\OrderUtil::remove_status_prefix(): Argument #1 ($status) must be of type string, null given, called in /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 629 and defined in /var/www/html/wp-content/plugins/woocommerce/src/Utilities/OrderUtil.php:239

Stack trace:

#0 /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(629): Automattic\WooCommerce\Utilities\OrderUtil::remove_status_prefix()

#1 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-order.php(286): WC_Abstract_Order->set_status()

#2 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-order.php(150): WC_Order->set_status()

#3 /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php(590): WC_Order->payment_complete()

#4 /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php(931): WC_Stripe_Payment_Gateway->process_response()

#5 /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php(667): WC_Stripe_UPE_Payment_Gateway->process_payment_with_deferred_intent()

#6 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1062): WC_Stripe_UPE_Payment_Gateway->process_payment()

#7 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1293): WC_Checkout->process_order_payment()

#8 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(520): WC_Checkout->process_checkout()

#9 /var/www/html/wp-includes/class-wp-hook.php(324): WC_AJAX::checkout()

#10 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()

#11 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()

#12 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action()

#13 /var/www/html/wp-includes/class-wp-hook.php(324): WC_AJAX::do_wc_ajax()

#14 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()

#15 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()

#16 /var/www/html/wp-includes/template-loader.php(13): do_action()

#17 /var/www/html/wp-blog-header.php(19): require_once('...')

#18 /var/www/html/index.php(17): require('...')

#19 {main}
 ```

**Comment by spencerfinnell** [comment]
Duplicate / resolved via https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3372

**Comment by mattallan** [comment]
Hi @karsey24 thanks for reporting the issue. As @spencerfinnell mentioned, this has been fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3376 and will be shipped in our next release - scheduled for 12th September (next week).
