### ISSUE TITLE
auto renewal generates fatal error - delete_meta_data() on null

### ISSUE THREAD

**Issue by dk-fbeckmann** [woocommerce/woocommerce-gateway-stripe#3679]
**Describe the bug**
After the latest update, subscription renewals that are due are not processed correctly and the order remains on hold. Manually creating renewal orders also leads to a fatal error.

**To Reproduce**
manual create renewal order 

**Expected behavior**
wc-completed renewal order and payment

**Environment (please complete the following information):**
 - WordPress Version: 6.7.1
 - WooCommerce Version: 9.5.1
 - Stripe Plugin Version: 9.00

**Additional context**
```
[24-Dec-2024 13:10:38 UTC] PHP Fatal error:  Uncaught Error: Call to a member function delete_meta_data() on null in /var/www/vhosts/site/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php:634
Stack trace:
#0 /var/www/vhosts/site/wp-includes/class-wp-hook.php(326): WC_Stripe_Payment_Gateway->delete_renewal_meta()
#1 /var/www/vhosts/site/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /var/www/vhosts/site/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-renewal-functions.php(38): apply_filters()
#3 /var/www/vhosts/site/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/admin/class-wcs-admin-meta-boxes.php(257): wcs_create_renewal_order()
#4 /var/www/vhosts/site/wp-includes/class-wp-hook.php(324): WCS_Admin_Meta_Boxes::create_pending_renewal_action_request()
#5 /var/www/vhosts/site/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /var/www/vhosts/site/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /var/www/vhosts/site/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php(183): do_action()
#8 /var/www/vhosts/site/wp-includes/class-wp-hook.php(324): WC_Meta_Box_Order_Actions::save()
#9 /var/www/vhosts/site/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#10 /var/www/vhosts/site/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /var/www/vhosts/site/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php(263): do_action()
#12 /var/www/vhosts/site/wp-includes/class-wp-hook.php(326): WC_Admin_Meta_Boxes->save_meta_boxes()
#13 /var/www/vhosts/site/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#14 /var/www/vhosts/site/wp-includes/plugin.php(517): WP_Hook->do_action()
#15 /var/www/vhosts/site/wp-includes/post.php(5060): do_action()
#16 /var/www/vhosts/site/wp-includes/post.php(5162): wp_insert_post()
#17 /var/www/vhosts/site/wp-admin/includes/post.php(453): wp_update_post()
#18 /var/www/vhosts/site/wp-admin/post.php(227): edit_post()
#19 {main}
  thrown in /var/www/vhosts/site/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php on line 634
```

**Comment by dk-fbeckmann** [comment]
internal problem
