### ISSUE TITLE
SQL issue during update 3.2.3=>4.1.7

### ISSUE THREAD

**Issue by nlienard** [woocommerce/woocommerce-gateway-stripe#691]
Wordpress: version 4.9.6–fr_FR

Before update woocommerce, here the versions: 

```
| woocommerce                                | active | available | 3.2.6   |
| woocommerce-gateway-stripe                 | active | available | 3.2.3   |
```

During update Process, got SQL error  on woocommerce-gateway-stripe :

```
root@galscw-www001:/var/www/galuser/lemagnetismepourtous.com/public_html# wp plugin update woocommerce --allow-root

Activation du mode maintenance...
Téléchargement de la mise à jour depuis https://downloads.wordpress.org/plugin/woocommerce.3.4.3.zip…
Décompression de la mise à jour...
Installation de la dernière version...
Retrait de l’ancienne version de l’extension...
L’extension a bien été mise à jour.
Désactivation du mode maintenance...
+-------------+-------------+-------------+---------+
| name        | old_version | new_version | status  |
+-------------+-------------+-------------+---------+
| woocommerce | 3.2.6       | 3.4.3       | Updated |
+-------------+-------------+-------------+---------+
Success: Updated 1 of 1 plugins.


root@galscw-www001:/var/www/galuser/lemagnetismepourtous.com/public_html# wp plugin update woocommerce-gateway-stripe --allow-root

Erreur de la base de données WordPress Can't create table `lemag592086`.`#sql-2da_37987` (errno: 150 "Foreign key constraint is incorrectly formed") pour la requête
                                        ALTER TABLE `fdjkUIJI_wc_download_log`
                                        ADD CONSTRAINT `fk_wc_download_log_permission_id`
                                        FOREIGN KEY (`permission_id`)
                                        REFERENCES `fdjkUIJI_woocommerce_downloadable_product_permissions` (`permission_id`) ON DELETE CASCADE;
                                 faite par include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::check_version, WC_Install::install, WC_Install::create_tables
Activation du mode maintenance...
Téléchargement de la mise à jour depuis https://downloads.wordpress.org/plugin/woocommerce-gateway-stripe.4.1.7.zip…
Décompression de la mise à jour...
Installation de la dernière version...
Retrait de l’ancienne version de l’extension...
L’extension a bien été mise à jour.
Désactivation du mode maintenance...
root@galscw-www001:/var/www/galuser/lemagnetismepourtous.com/public_html#
```
Trying to fix with mysql:

```
MariaDB [(none)]> use lemag592086
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [lemag592086]> ALTER TABLE `fdjkUIJI_wc_download_log`  ADD CONSTRAINT `fk_wc_download_log_permission_id`  FOREIGN KEY (`permission_id`)  REFERENCES `fdjkUIJI_woocommerce_downloadable_product_permissions` (`permission_id`) ON DELETE CASCADE;
ERROR 1005 (HY000): Can't create table `lemag592086`.`#sql-2da_379e3` (errno: 150 "Foreign key constraint is incorrectly formed")
MariaDB [lemag592086]> desc fdjkUIJI_wc_download_log;
+-----------------+---------------------+------+-----+---------+----------------+
| Field           | Type                | Null | Key | Default | Extra          |
+-----------------+---------------------+------+-----+---------+----------------+
| download_log_id | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| timestamp       | datetime            | NO   | MUL | NULL    |                |
| permission_id   | bigint(20) unsigned | NO   | MUL | NULL    |                |
| user_id         | bigint(20) unsigned | YES  |     | NULL    |                |
| user_ip_address | varchar(100)        | YES  |     |         |                |
+-----------------+---------------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)

```

Current version:

```
| woocommerce                                | active | none   | 3.4.3   |
| woocommerce-gateway-stripe                 | active | none   | 4.1.7   |
```

Web GUI returns the following error about APPLE PAY: 

```
La vérification du domaine Apple Pay a échoué. Vérifiez le journal pour voir le problème. (L’enregistrement doit être activé pour voir les journaux enregistrés)
```

LOG

```
root@galscw-www001:/var/www/galuser/lemagnetismepourtous.com/public_html# tail -f ./wp-content/uploads/wc-logs/fatal-errors-c2688eee37b5003f04ac1a3ec0b4d582.log

2018-06-28T18:15:16+02:00 CRITICAL Uncaught Error: Call to undefined function request_filesystem_credentials() in /var/www/galuser/lemagnetismepourtous.com/public_html/wp-admin/includes/class-wp-upgrader-skin.php:93
Stack trace:
#0 /var/www/galuser/lemagnetismepourtous.com/public_html/wp-admin/includes/class-automatic-upgrader-skin.php(47): WP_Upgrader_Skin->request_filesystem_credentials(false, '/var/www/galuse...', true)
#1 /var/www/galuser/lemagnetismepourtous.com/public_html/wp-admin/includes/class-wp-automatic-updater.php(144): Automatic_Upgrader_Skin->request_filesystem_credentials(false, '/var/www/galuse...', true)
#2 /var/www/galuser/lemagnetismepourtous.com/public_html/wp-admin/includes/update.php(85): WP_Automatic_Updater->should_update('core', Object(stdClass), '/var/www/galuse...')
#3 /var/www/galuser/lemagnetismepourtous.com/public_html/wp-includes/update.php(215): find_core_auto_update()
#4 /var/www/galuser/lemagnetismepourtous.com/public_html/wp-includes/class-wp-hook.php(286): wp_version_check()
#5 /var/www/galuser/lemagnetisme
```
Any clue is welcome.

Thanks

**Comment by roykho** [comment]
Sorry but db issues are not related to Stripe.

**Comment by nlienard** [comment]
but the SQL error occured during the update of this plugin, why is not related ?

```
root@galscw-www001:/var/www/galuser/lemagnetismepourtous.com/public_html# wp plugin update woocommerce-gateway-stripe --allow-root

Erreur de la base de données WordPress Can't create table `lemag592086`.`#sql-2da_37987` (errno: 150 "Foreign key constraint is incorrectly formed") pour la requête
                                        ALTER TABLE `fdjkUIJI_wc_download_log`
                                        ADD CONSTRAINT `fk_wc_download_log_permission_id`
                                        FOREIGN KEY (`permission_id`)
                                        REFERENCES `fdjkUIJI_woocommerce_downloadable_product_permissions` (`permission_id`) ON DELETE CASCADE;
                                 faite par include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::check_version, WC_Install::install, WC_Install::create_tables
Activation du mode maintenance...
```

**Comment by roykho** [comment]
Stripe doesn't create any tables or work with the DB at all. I would suggest you update it manually by FTPing it and activate instead of auto update.

**Comment by nlienard** [comment]
it is not auto-update, i did the manual update with wp cli :1st_place_medal: 
```
wp plugin update woocommerce-gateway-stripe
```

Should i reinstall the extension ?

**Comment by roykho** [comment]
Yes do manual update with FTP or SSH downloading it from .org and activate it. Don't use update.
